server:
  port: 8771
  
spring:
  application:
    name: API-GATEWAY
    
    
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: http://localhost:8880 
        predicates:
        - Path=/api/v1/users/**
        
      - id: PRODUCT-SERVICE
        uri: http://localhost:8881 
        predicates:
        - Path=/product/**  

      - id: ORDER-SERVICE
        uri: http://localhost:8882 
        predicates:
        - Path=/order/** 
        
      - id: PAYMENT-SERVICE
        uri: http://localhost:8883 
        predicates:
        - Path=/payment/**  


eureka:
  instance: 
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  